name: driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Firebase
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  flutter_local_notifications: ^19.5.0

  #common
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  country_code_picker: ^3.4.1
  syncfusion_flutter_charts: ^31.2.12
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  uuid: ^4.5.2
  nb_utils: ^7.1.8
  url_launcher: ^6.3.2
  dotted_border: ^3.1.0
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  flutter_image_compress: ^2.4.0
  flutter_widget_from_html: ^0.17.1
  flutter_screenutil: ^5.9.3
  flutter_otp_text_field: ^1.5.1+1
  timelines_plus: ^1.0.8
  flutter_slidable: ^4.0.3
  flutter_rating_bar: ^4.0.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file: ^3.5.10
  syncfusion_flutter_datepicker: ^31.2.12
  share_plus: ^12.0.1

  #payment_dependencies
  flutter_stripe: ^12.1.1
  razorpay_flutter: ^1.4.0
  mercadopago_sdk: ^1.3.0
  http_auth: ^1.0.4

  #login
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # Google Map
  flutter_polyline_points: ^3.1.0
  google_maps_flutter: ^2.14.0
  googleapis_auth: ^2.0.0
  location: ^8.0.1
  app_settings: ^6.1.1

  geolocator: ^14.0.2
  geoflutterfire2: ^2.3.15
  permission_handler: ^12.0.1
  mailer: ^6.6.0
  flutter_dash: ^1.0.0

dependency_overrides:
  http: ^1.6.0
  flutter_svg: ^2.2.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animation/

  fonts:
    - family: Gilmer Bold
      fonts:
        - asset: assets/fonts/Gilmer Bold.otf

    - family: Gilmer Medium
      fonts:
        - asset: assets/fonts/Gilmer Medium.otf


    - family: Gilmer Regular
      fonts:
        - asset: assets/fonts/Gilmer Regular.otf

    - family: Satoshi-Black
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf

    - family: Satoshi-BlackItalic
      fonts:
        - asset: assets/fonts/Satoshi-BlackItalic.otf

    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf

    - family: Satoshi-BoldItalic
      fonts:
        - asset: assets/fonts/Satoshi-BoldItalic.otf

    - family: Satoshi-Italic
      fonts:
        - asset: assets/fonts/Satoshi-Italic.otf

    - family: Satoshi-Light
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf

    - family: Satoshi-LightItalic
      fonts:
        - asset: assets/fonts/Satoshi-LightItalic.otf

    - family: Satoshi-Medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf

    - family: Satoshi-MediumItalic
      fonts:
        - asset: assets/fonts/Satoshi-MediumItalic.otf

    - family: Satoshi-Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf

